<?php
declare(strict_types=1);

namespace J\Money;

class Yen extends AnyCurrency
{

    public function __construct(string $symbol, string $isoCode, string $shortName, string $fullName, float $decimalPlaces)
    {
        parent::__construct($symbol, $shortName, $fullName, $decimalPlaces);
        parent::setCode($isoCode);
    }

    public function yenShouldNotConatainDecimalPlaces(float $decimalPlaces)
    {
        $str = (string)$decimalPlaces;
        $amountStrLength = explode(".", $str);
        if (strlen($amountStrLength[1]) > 0) {
            throw new \InvalidArgumentException("yen should not contain decimal places!", 1004);
        }
        $this->decimalPlaces = $decimalPlaces;
    }
    public function code(): string
    {
        return parent::code(); // TODO: Change the autogenerated stub
    }

    public function name(): string
    {
        return parent::name(); // TODO: Change the autogenerated stub
    }

    public function fullName(): string
    {
        return parent::fullName(); // TODO: Change the autogenerated stub
    }

    public function sign(): string
    {
        return parent::sign(); // TODO: Change the autogenerated stub
    }


    /**
     * @return mixed
     */
    public function getDecimalPlaces()
    {
        return $this->decimalPlaces;
    }

    /**
     * @return mixed
     */
    public function getFullName()
    {
        return $this->fullName;
    }

}